### ISSUE TITLE
What packages are required?

### ISSUE THREAD

**Issue by jakobvonessen** [Tempaccnt/Termux-alpaca#1]
Hi!

On a fresh install of Termux, I ran into the issue of gig not being installed and had to use `pkg install x11-repo`, then `pkg install git` to be able to clone the repo.

When launching install-alpaca-Android.sh, I get additional missing packages:

```
CANNOT LINK EXECUTABLE "cc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
make: *** [Makefile:186: ggml.o] Error 1
CANNOT LINK EXECUTABLE "wget": library "libssl.so.3" not found: needed by main executable
```

Running pkg install wget doesn't find it in any repositories. What additional repositories do I need to be able to run the whole script?

Thanks!
Jakob

**Comment by Tempaccnt** [comment]
you only need to install git to clone this repository. the rest of the required packages will be installed once you run the script. I will update the readme page so that you only need to copy the codes there and it will setup everything for you.

basicaly to install git you don't need x11-repo. just run the following:
```
pkg update && pkg upgrade -y
pkg install git

```

alternativaly, you could download the script directly from the releases then move it to your termux home directory by running this:
```
termux-setup-storage
mv /storage/emulated/0/"the path to the downloaded script without quotes" /$HOME

```
this way you don't need to install any packages. the script will install them for you after running it.

**Comment by jakobvonessen** [comment]
Thanks, running
```
apt purge science-repo
apt purge game-repo
```
and then your suggestion worked! :)
